name: Format

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/format.yml'
      - 'server/**'
  pull_request:
    paths:
      - '.github/workflows/format.yml'
      - 'server/**'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
        # Pinned to axel-op/googlejavaformat-action@v4.0.0
      - uses: axel-op/googlejavaformat-action@c1134ebd196c4cbffb077f9476585b0be8b6afcd
        name: Format
        with:
          release-name: v1.28.0
          args: "--set-exit-if-changed --dry-run"
